apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: step-final-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/a3888s/step-final.git'
    targetRevision: main
    path: app/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
